"""Sincronización con base de datos existente

Revision ID: 05a0dca010e4
Revises: b4146ec3e710
Create Date: 2025-04-10 20:56:23.853378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '05a0dca010e4'
down_revision: Union[str, None] = 'b4146ec3e710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recetas_categorias',
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('receta_id', 'categoria_id')
    )
    op.drop_table('recetas_categoria')
    op.drop_index('nombre', table_name='alergias')
    op.drop_table('alergias')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alergias',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('nombre', 'alergias', ['nombre'], unique=True)
    op.create_table('recetas_categoria',
    sa.Column('receta_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('categoria_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], name='recetas_categoria_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], name='recetas_categoria_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('receta_id', 'categoria_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('recetas_categorias')
    # ### end Alembic commands ###
