"""Cambiamos el tiempo de cocion a solo string

Revision ID: b4146ec3e710
Revises: c190b91d3d60
Create Date: 2025-04-10 17:59:05.466782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b4146ec3e710'
down_revision: Union[str, None] = 'c190b91d3d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('nombre', table_name='alergias')
    op.drop_table('alergias')
    op.drop_table('receta_alergias')
    op.alter_column('recetas', 'tiempo_cocina',
               existing_type=mysql.JSON(),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recetas', 'tiempo_cocina',
               existing_type=sa.String(length=100),
               type_=mysql.JSON(),
               existing_nullable=False)
    op.create_table('receta_alergias',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('receta_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alergia_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['alergia_id'], ['alergias.id'], name='receta_alergias_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], name='receta_alergias_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('alergias',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('nombre', 'alergias', ['nombre'], unique=True)
    # ### end Alembic commands ###
