"""Añadir columna descripcion_original a recetas

Revision ID: c190b91d3d60
Revises: cb48272f9ee8
Create Date: 2025-04-09 19:28:13.401154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c190b91d3d60'
down_revision: Union[str, None] = 'cb48272f9ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recetas', sa.Column('descripcion_original', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recetas', 'descripcion_original')
    # ### end Alembic commands ###
